### ISSUE TITLE
very nice but is not working

### ISSUE THREAD

**Issue by elgransan** [ntxinh/AspNetCore-DDD#1]
Using Visual Studio 2019 starts but only work Swagger. I get:

Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

When trying any api url.
 
I tried adding to appsetings.json 

  "ConnectionStrings": {
    "DefaultConnection": "Data Source=.;Initial Catalog=ddd1;Integrated Security=True"
  }

with a new empty database, but I'm getting the same error

**Comment by ntxinh** [comment]
Hi @elgransan 
I will provide a guide with more detail
Hope you can get work with it

Step 1:
Run SQL Script in `./Sql/GenerateDataBase.sql`
This script will create a new database with the name 'DDD'

Step 2:
Edit the file `./Src/DDD.Services.Api/appsettings.Development.json`
Update it with your credential to your SQL Server

Step 3:
If you use Visual Studio with IIS Express, make sure you selected 'Dev - IIS Express' profile
You can click Run now

Hope I can hear the good news from you
Thank you
