### ISSUE TITLE
How to map with AutoMapper for AspNet Identity Core

### ISSUE THREAD

**Issue by eduar2083** [ntxinh/AspNetCore-DDD#2]
For example if I have:
```
var Users = await UserManager.Users.ToListAsync();
return Response(Users);
```
This exposes all the fields of the ApplicationUser entity, however I only want to expose a few fields and would like to do using AutoMapper.

Help me please. Thanks!

**Comment by ntxinh** [comment]
Hi @eduar2083 
You can use like this

```csharp
// Add this to your AutoMapperProfile
CreateMap<Users, UserViewModel>();
```

```csharp
var users = await UserManager.Users.ToListAsync();
var userVm = _mapper.Map<IList<Users>, IList<UserViewModel>>(users).ToList();
return Response(userVm);
```

and also learn more on https://docs.automapper.org/en/latest/

Thank you
